export const Data = [
  {
    Title: "Feel: A Digital Therapeutic Solution for Mental Health",
    Author: "Nikita Farhin",
    Body: "Mental illnesses affect 19% of the adult population, <img src=\"https://picsum.photos/200/300\" /> 46% of teenagers, and 13% of children each year. People struggling with their mental health may be in our family, living next door, or in our workplaces. However, only half of those affected receive treatment, often because of the stigma attached to mental health. Untreated, mental illness can contribute to higher medical expenses, poorer performance at school and work, fewer employment opportunities, and increased risk of suicide. It's very important to remember that just because one may not know exactly what causes someone to experience a mental health problem, this doesn't mean that it is any less serious than any other illness, any less deserving of recognition and treatment, or any easier to recover from. Most potential mental health problems will not become mental health problems if one response to them early. Sentio Solutions is a San Francisco based startup that develops digital biomarkers and therapeutics to change the way of diagnosing, monitoring, and caring  for mental health. People suffering from anxiety, depression, and bipolar disorders need continuous monitoring and support tools, to help them manage their own emotions and track all changes in emotional habits or patterns on a daily basis. In today’s busy world, mental health issues are often overlooked. So, a startup like this is a really good initiative in order to create a mentally healthy community.  For people with mental health issues, the social stigma and discrimination they experience can worsen their problems, making it all the more difficult to recover. It may cause the person to feel ashamed, hopeless, isolated, and thus, avoid getting the help they need because of the fear of being stigmatized.  Here, the emotion-sensing wristband, Feel along with the app comes to the rescue. Feel is a wearable wristband that leverages proprietary algorithms to recognize and track human emotions throughout the day. At the same time, the mobile application provides actionable recommendations based on advanced psychological techniques, to help users develop positive emotional habits and achieve wellbeing. Feel consists of 3 parts: the wristband, the emotion recognition algorithms, and the mobile application. This particular program helps one to develop positive emotional habits through a combination of emotion sensors and evidence-based techniques. It provides dedicated licensed therapists to each individual with depression and anxiety for real-time monitoring and personalized interventions. This way the program brings an end to all the inner battles of a person with himself/herself and the society. These inner battles go so unnoticed, yet have such a significant impact on one's life. This program has fascinated me the most because of its simplicity and effectiveness. It gives one the opportunity to overcome any mental obstacles and lead a mentally happy and healthy life.",
  },
  {
    Title: "Article Heading",

    Body: '"Begin today" Thats all the note said. There was no indication from where it came or who may have written it. Had it been meant for someone else? Meghan looked around the room, but nobody made eye contact back. For a brief moment, she thought it might be a message for her to follow her dreams, but ultimately decided it was easier to ignore it as she crumpled it up and threw it away.',
  },
  {
    Title: "Article Heading",
    Body: '"Begin today" Thats all the note said. There was no indication from where it came or who may have written it. Had it been meant for someone else? Meghan looked around the room, but nobody made eye contact back. For a brief moment, she thought it might be a message for her to follow her dreams, but ultimately decided it was easier to ignore it as she crumpled it up and threw it away.',
  },
  {
    Title: "Article Heading",
    Body: '"Begin today" Thats all the note said. There was no indication from where it came or who may have written it. Had it been meant for someone else? Meghan looked around the room, but nobody made eye contact back. For a brief moment, she thought it might be a message for her to follow her dreams, but ultimately decided it was easier to ignore it as she crumpled it up and threw it away.',
  },
];
